### PR TITLE
Feat/register with password

### LINKED ISSUE #112: Register new bots using email and password
To make it easier to use the same bot over and over, even if you forget the token.

### PR DESCRIPTION
**Pull request by ForsbergPhilip**
Added password to botRegistry.

Added new endpoint `/api/bots/recover` to fetch bot information.

Modified example bots.

Don't deploy this before we have tls cert!

Closes #112

### CODE REVIEW

**Comment by indrif** [comment]
How will this work for old bots? Or should we basically not allow the old ones to play again? What about their associated emails and such, perhaps they want to use it in another season?

**Comment by ForsbergPhilip** [comment]
We could either just delete all old bots or create an endpoint where they can set a password if they have saved the token.

Think its better to just delete all old bots. We still have the highscores saved from the old seasons.

**Comment by indrif** [comment]
But if we delete old bots then how does it work with high scores? They are only connected by name but then that mean someone can register a new bot and highjack another top players name

Skickat från min iPhone

**Comment by indrif** [comment]
Maybe we could also create a password for all old bots and use their token as password and then just regenerate a new token for everyone. Then they can use their old token as password if they have it saved somewhere 

Skickat från min iPhone

**Comment by ForsbergPhilip** [comment]
`But if we delete old bots then how does it work with high scores? They are only connected by name but then that mean someone can register a new bot and highjack another top players name`
Correct! 

`Maybe we could also create a password for all old bots and use their token as password and then just regenerate a new token for everyone. Then they can use their old token as password if they have it saved somewhere`
Yes, but if they don't remember the token they can't get access to the bot with their registered email again.

`Is this backwards compatible?`
I had some problems with pg_dump (different versions) so I just copied bot_registrations table to bot_registrations_old. Will add a query in down (revert) where we insert all the rows again.

**Comment by ForsbergPhilip** [comment]
We could also just add this "create an endpoint where they can set a password if they have saved the token." 

They just can't access the bot if they have forgotten the token.

**Comment by ForsbergPhilip** [comment]
Talked to Lukas and Affe. We agreed that we should just delete all the old bots. They have to create the bot again if they want to play. Someone else might take their botName, but then they have to choose another name.

**Comment by ForsbergPhilip** [comment]
Waiting with deploy. Might cause some issues if we add school icons and someone from another school registers with

**Comment by ForsbergPhilip** [comment]
Changing to this: Add password nullable. Create endpoint where users can add a password if they have the correct token.
By doing this bots won't end up getting wrong team logos in the highscore list.

**Pull request merged**
